language: java
env:
  global:
    - BASE_VERSION_NUMBER="0.4"
    - NEXUS_REPOSITORY_ID="htb-nexus"
    - secure: N0ZCUpX5yYzwhYG20OqN5JwFjOJleHFPtA71Easy+QLDIXKE4nb10R7fBzbfQDSkVU4XPDD5t1vh88Jqyt+9mpKigfyGZJi7Lpx1U9a5+Xw8VzCiNOCX/+xBy8nFmF/pIAM3D0d02JX5b7fl8U6bHv+jVIxlhGpx+5ENJx5m3vM=
before_install:
  - mvn versions:set versions:commit -DnewVersion=$BASE_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
script:
  - mvn compile findbugs:check
  - mvn clean package
after_success:
  - ./travis/deploy.sh >/dev/null
